name: linter

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

permissions:
  contents: write

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install

      - name: Rector Cache
        uses: actions/cache@v4
        with:
          path: /tmp/rector
          key: ${{ runner.os }}-rector-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-rector-
      - run: mkdir -p /tmp/rector

      - name: PHPStan Cache
        uses: actions/cache@v4
        with:
          path: /tmp/phpstan
          key: ${{ runner.os }}-phpstan-${{ hashFiles('composer.lock') }}
          restore-keys: ${{ runner.os }}-phpstan-
      - run: mkdir -p /tmp/phpstan

      - name: Format and Lint Code
        run: composer lint

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
         commit_message: Applies automatic formatter and linter fixes
         commit_options: '--no-verify'
